apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
spec:
  selector:
    app: node-backend
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: http
    port: 5000
    targetPort: 3010
    nodePort: 31110
  - protocol: TCP
    name: https
    port: 5443
    targetPort: 3443
    nodePort: 31443
